import { useState } from 'react'
import { Sparkles, CheckCircle2, Circle, GripVertical, Plus, Calendar } from 'lucide-react'
import DashboardLayout from '../components/layout/DashboardLayout'

type Props = { onNavigate: (page: string) => void }

const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
const dates = ['Jun 9', 'Jun 10', 'Jun 11', 'Jun 12', 'Jun 13', 'Jun 14', 'Jun 15']

interface Task { id: number; subject: string; topic: string; duration: string; done: boolean; color: string }

const initialTasks: Task[][] = [
  [{ id: 1, subject: 'Physics',     topic: "Newton's Laws — Revision",        duration: '45 min', done: false, color: 'bg-primary/10 text-primary' }],
  [{ id: 2, subject: 'Mathematics', topic: 'Quadratic Equations Practice',    duration: '60 min', done: false, color: 'bg-accent-mint/10 text-accent-mint' },
   { id: 3, subject: 'English',     topic: 'Essay Writing Techniques',        duration: '30 min', done: false, color: 'bg-amber-50 text-amber-600' }],
  [{ id: 4, subject: 'Chemistry',   topic: 'Periodic Table & Trends',         duration: '45 min', done: false, color: 'bg-red-50 text-red-500' }],
  [{ id: 5, subject: 'Physics',     topic: 'Work, Energy and Power Problems', duration: '60 min', done: false, color: 'bg-primary/10 text-primary' },
   { id: 6, subject: 'Mathematics', topic: 'Trigonometry Problems',           duration: '45 min', done: false, color: 'bg-accent-mint/10 text-accent-mint' }],
  [{ id: 7, subject: 'Biology',     topic: 'Cell Division — Meiosis',         duration: '50 min', done: false, color: 'bg-green-50 text-green-600' }],
  [{ id: 8, subject: 'Physics',     topic: 'Past WAEC Questions (2015–2020)', duration: '90 min', done: false, color: 'bg-primary/10 text-primary' }],
  [],
]

export default function AIStudyPlanPage({ onNavigate }: Props) {
  const [tasks, setTasks] = useState(initialTasks)

  function toggleTask(dayIdx: number, taskId: number) {
    setTasks(prev => prev.map((dayTasks, i) =>
      i === dayIdx ? dayTasks.map(t => t.id === taskId ? { ...t, done: !t.done } : t) : dayTasks
    ))
  }

  const totalTasks = tasks.flat().length
  const doneTasks  = tasks.flat().filter(t => t.done).length

  return (
    <DashboardLayout
      activePage="ai-tutor"
      onNavigate={onNavigate}
      title="AI Study Plan"
      subtitle="Your personalised weekly schedule for exam prep"
    >
      <div className="flex flex-col gap-6">

        {/* AI info banner */}
        <div className="bg-primary/8 border border-primary/20 rounded-card p-4 flex items-start gap-3">
          <Sparkles size={16} className="text-primary mt-0.5 shrink-0" />
          <div>
            <p className="text-sm font-semibold text-foreground">Generated by AI Tutor</p>
            <p className="text-xs text-muted mt-0.5">
              Based on your weak areas (Physics 61%, Mathematics 58%) and upcoming exams on Jun 15.
              Drag tasks to reorder. Click the circle to mark complete.
            </p>
          </div>
        </div>

        {/* Progress */}
        <div className="bg-surface rounded-card shadow-sm p-5">
          <div className="flex items-center justify-between mb-3">
            <p className="text-sm font-semibold text-foreground">Week Progress</p>
            <p className="text-sm font-bold text-primary">{doneTasks}/{totalTasks} tasks</p>
          </div>
          <div className="h-2.5 bg-black/8 rounded-full overflow-hidden">
            <div className="h-full bg-primary rounded-full transition-all" style={{ width: `${Math.round((doneTasks / totalTasks) * 100)}%` }} />
          </div>
        </div>

        {/* Weekly grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">
          {days.slice(0, 7).map((day, i) => (
            <div key={day} className="bg-surface rounded-card shadow-sm overflow-hidden">
              <div className="px-4 py-3 border-b border-black/6 flex items-center justify-between">
                <div>
                  <p className="text-sm font-bold text-foreground">{day}</p>
                  <p className="text-xs text-muted">{dates[i]}</p>
                </div>
                <div className="flex items-center gap-1 text-xs text-muted">
                  <Calendar size={11} />
                  <span>{tasks[i].length} {tasks[i].length === 1 ? 'task' : 'tasks'}</span>
                </div>
              </div>
              <div className="p-3 flex flex-col gap-2 min-h-[80px]">
                {tasks[i].length === 0 ? (
                  <p className="text-xs text-muted text-center py-4">Rest day</p>
                ) : (
                  tasks[i].map(task => (
                    <div key={task.id} className="flex items-start gap-2 group cursor-pointer" onClick={() => toggleTask(i, task.id)}>
                      <GripVertical size={12} className="text-muted/40 mt-0.5 cursor-grab hidden group-hover:block shrink-0" />
                      <button className="mt-0.5 shrink-0">
                        {task.done
                          ? <CheckCircle2 size={15} className="text-green-500" />
                          : <Circle size={15} className="text-muted/40" />}
                      </button>
                      <div className="min-w-0">
                        <span className={`inline-block text-[10px] font-semibold px-2 py-0.5 rounded-full mb-1 ${task.color}`}>
                          {task.subject}
                        </span>
                        <p className={`text-xs leading-snug ${task.done ? 'line-through text-muted' : 'text-foreground'}`}>
                          {task.topic}
                        </p>
                        <p className="text-[10px] text-muted mt-0.5">{task.duration}</p>
                      </div>
                    </div>
                  ))
                )}
                <button className="flex items-center gap-1 text-[10px] text-muted hover:text-primary transition-colors mt-1">
                  <Plus size={10} /> Add task
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </DashboardLayout>
  )
}
